default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: coffeeshop_development

test:
  <<: *default
  database: coffeeshop_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: coffeeshop_production
